### ISSUE TITLE
Deprecated Atom APIs will be removed June 1st

### ISSUE THREAD

**Issue by benogle** [tomkadwill/atom-rails#23]
Atom will no longer load this package after June 1st without changes. There are a couple deprecations on the latest version (`0.4.0`) of this package:
1. Store package style sheets in the `styles/` directory instead of `stylesheets/` in the `<pack-name>` package
2. Use `activationCommands` instead of `activationEvents` in your package.json Commands should be grouped by selector as follows: `json "activationCommands": { "atom-workspace": ["foo:bar", "foo:baz"], "atom-text-editor": ["foo:quux"] }`
3. atom.workspaceView is no longer available. In most cases you will not need the view. See the Workspace docs for alternatives: https://atom.io/docs/api/latest/Workspace. If you do need the view, please use `atom.views.getView(atom.workspace)`, which returns an HTMLElement.
4. Call ::getActiveTextEditor instead
5. Use ::getPaths instead

Visit https://gist.github.com/benogle/6d09e295c84b717ef9b4 and search for your package name to see up-to-date deprecations.

If this package has been replaced by another package or functionality in core, please reply with this information.

See https://github.com/atom/atom/issues/6867 for more info. Thanks!

**Comment by amiuhle** [comment]
@tomkadwill The package is not loading any more. Are you still maintaining this package?

**Comment by tomkadwill** [comment]
I'm not actively maintaining this package anymore. I believe it has been removed as of June 1st

**Comment by mdxprograms** [comment]
Is there a similar package to use?

**Comment by amiuhle** [comment]
@tomkadwill can you add me as a collaborator?

**Comment by tomkadwill** [comment]
@amiuhle Yep. Done
