### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by suryakhattri** [tomkadwill/atom-rails#24]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.

```
Atom.Object.defineProperty.get (/usr/share/atom/resources/app/src/atom.js:54:11)
Object.activate (/home/skhattri/.atom/packages/atom-rails/lib/atom-rails.coffee:9:9)
```

**Comment by tomkadwill** [comment]
Hi @suryakhattri, closing this as the package is no longer supported or available for Atom. Sorry for the delay in getting back to you :)
