### ISSUE TITLE
Cannot find the atom-rails package for Atom 1.1.0

### ISSUE THREAD

**Issue by mrthebob** [tomkadwill/atom-rails#25]

**Comment by v3rtx** [comment]
Same for version 1.12.7 @tomkadwill does your package still supported in current version of atom?

**Comment by tomkadwill** [comment]
Hi @mrthebob and @v3rtx. My package is no longer supported. I think this is a good alternative: https://atom.io/packages/rails-transporter

**Comment by v3rtx** [comment]
Thank you @tomkadwill this is what I was looking for
